name: Run a notebook within its repo on PRs

on:
  push:
    branches:
      - main
      
env:
  DATABRICKS_HOST: https://adb-7871370843959004.4.azuredatabricks.net/
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks out the repo
        uses: actions/checkout@v2
      - name: Log into Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
        
      # The step below does the following:
      # 1. Sends a POST request to generate an Azure Active Directory token for an Azure service principal
      # 2. Parses the token from the request response and then saves that in as DATABRICKS_TOKEN in the
      # GitHub enviornment.
      # Note: if the API request fails, the request response json will not have an "access_token" field and
      # the DATABRICKS_TOKEN env variable will be empty.
      - name: Generate and save AAD token
        id: generate-token
        run: |
          echo "DATABRICKS_TOKEN=$(az account get-access-token \
          --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d \
          --query accessToken -o tsv)" >> $GITHUB_ENV
      - name: create Cluster
        run: |
          databricks clusters create --json-file ADB/Clusters/computeengine.json
      - name: import runbook
        run: |   
          databricks workspace import /ADB/Notebook/DataRead.py /Shared/Automation/DataRead.py -l PYTHON

