on:
  push:
    branches:
      - adf_publish
      - main

name: AzureDataFactorySync

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.9
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
        scope: resourcegroup
        # Override the Subscription Id set by Azure Login.
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        # Provide the name of a resource group, only required for resource Group deployments.
        resourceGroupName: ${{ secrets.AZURE_RG }}
        # Specify the path or URL to the Azure Resource Manager template.
        template: ./adf-automation-test1/ARMTemplateForFactory.json
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
        deploymentMode: Incremental
        # Specifies the name of the resource group deployment to create.
        deploymentName: 'ADFSync'
        # Supply deployment parameter values.
        parameters: CosmosDbNoSql1_connectionString = ${{ secrets.COSMOS_DB_Connection }}
                    AzureBlobStorage1_connectionString = ${{ secrets.Storage_Connection }}
                    factoryName = 'adf-automation-test2'
                    containerUri = ${{ secrets.CONTAINER_URL}}
                    containerSasToken = ${{ secrets.Container_SAS}}
        # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
        failOnStdErr: true
