on:
  push:
    branches:
      - adf_publish
      - main

name: AzureDataFactorySync

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
